name: 'Common Steps'
description: 'Common steps for all workflows'
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          node_modules/
        key: ${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js v20.10.0
      uses: actions/setup-node@v4
      with:
        node-version: v20.10.0
        cache: 'pnpm'
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - run: pnpm config set store-dir .pnpm-store
      shell: bash
