name: CI Pipeline

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ['Create release']
    types: [completed]

jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0
      - name: checkout branch
        run: |
          branch_name="release/${{ steps.previoustag.outputs.tag }}"
          git checkout $branch_name
      - name: Read output
        id: read-output
        run: |
          echo "${{ steps.previoustag.outputs.tag }}"
  
  install-dependencies:
    runs-on: ubuntu-22.04
    needs: checkout-branch
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-steps
      - run: pnpm install --no-frozen-lockfile
  
  build-app:
    needs: install-dependencies
    uses: ./.github/workflows/template-build.yml
    with:
      run: pnpm
      build-script: build
      artifact-name: build-app
      artifact-path: build

  merge-branch:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: "release/${{ needs.checkout-branch.outputs.release_version }}"
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  