name: CI Pipeline

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        run: |
          branch_name="release/${{ github.ref_name }}"
          git checkout $branch_name

  install-dependencies:
    runs-on: ubuntu-22.04
    needs: checkout-branch
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-steps
      - run: pnpm install --no-frozen-lockfile
  
  build-app:
    needs: install-dependencies
    uses: ./.github/workflows/template-build.yml
    with:
      run: pnpm
      build-script: build
      artifact-name: build-app
      artifact-path: build

  merge-branch:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: "release/${{ github.ref_name }}"
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  