name: CI Pipeline

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: ['Create release']
    types: [completed]

jobs:
  checkout_branch:
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_version.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0

      - uses: actions/github-script@v7
        id: get_version
        env:
          current_version: ${{ steps.previoustag.outputs.tag }}
        with:
          script: |
            const { current_version } = process.env
            const versionArr = current_version.split('.')
            versionArr[versionArr.length - 1] = 0
            const result = versionArr.join('.')
            return result

      - name: checkout branch
        run: |
          branch_name="release/${{ steps.get_version.outputs.result }}"
          git checkout $branch_name
  
  install-dependencies:
    runs-on: ubuntu-22.04
    needs: checkout_branch
    steps:
      - uses: ./.github/actions/common-steps
      - run: pnpm install --no-frozen-lockfile
  
  build-app:
    needs: install-dependencies
    uses: ./.github/workflows/template-build.yml
    with:
      run: pnpm
      build-script: build
      artifact-name: build-app
      artifact-path: build

  merge-branch:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - env:
          OUTPUT1: ${{needs.checkout_branch.outputs.release_version}}
        run: echo "$OUTPUT1"
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: "release/${{ needs.checkout-branch.outputs.release_version }}"
          target_branch: 'main'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

  