name: Create release

on:
  pull_request:

jobs:
  your-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Output latest commit message
      run: |
        echo "Latest Commit Message: ${{ github.event.head_commit.message }}"
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        HEAD_COMMIT_MESSAGE=$(git show -s --format=%s)
        echo "Commit Message: $COMMIT_MESSAGE"
        echo "HEAD Commit Message: $HEAD_COMMIT_MESSAGE"
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: test if
      if: contains(env.COMMIT_MESSAGE, '[e2e]')
      run: |
        echo "contain [e2e]"