name: Create release

on:
  pull_request:

jobs:
  your-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    
    - name: Output latest commit message
      run: |
        # Fetch the PR branch's latest commit using the SHA
        # git fetch origin ${{ github.event.pull_request.head.sha }}
        git checkout ${{ github.event.pull_request.head.sha }}
        # Extract the commit message
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Commit Message: $COMMIT_MESSAGE"
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

    - name: test if
      if: contains(env.COMMIT_MESSAGE, '[e2e]')
      run: |
        echo "contain [e2e]"