name: Create release

on:
  workflow_dispatch:

jobs:
  your-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create Branch
      run: |
        branch_name="release/${{ steps.semvers.outputs.minor }}"
        git checkout -b $branch_name
        git push --set-upstream origin $branch_name

    - name: Generate Release Tag
      uses: mokhlesurr031/github-manual-release@v2.0.2
      with:
        release-tag-number: ${{ steps.semvers.outputs.minor }}
        user-email: "${{ github.actor }}"
        user-name: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        github-token: ${{ secrets.GITHUB_TOKEN }}
