name: Create release

on:
  pull_request:

jobs:
  your-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

  get-commit-message:
    runs-on: ubuntu-latest
    needs: your-job
    outputs:
      last_commit_message: ${{ steps.get-commit-message.outputs.contains_e2e }}
    steps:
    - uses: actions/checkout@v4
    - name: Output latest commit message
      id: get-commit-message
      run: |
        git fetch origin ${{ github.event.pull_request.head.sha }}
        git checkout ${{ github.event.pull_request.head.sha }}
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Commit Message: $COMMIT_MESSAGE"
        echo "commit-message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

  test-e2e:
    runs-on: ubuntu-latest
    needs: get-commit-message 
    steps:
    - name: test if
      if: contains(needs.get-commit-message.outputs.last_commit_message, '[e2e]')
      run: |
        echo "contain [e2e]"