name: Create release

on:
  pull_request:

jobs:
  your-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 0.1.0

    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: check commit message
      id: commit_message
      run: |
        commit=${{ github.event.commits[0] }}
        message=${{ github.event.commits[0].message }}
        contains(github.event.commits[0].message, '[e2e]')
        echo "${commit}"
        echo "${message}"
        echo "${message}"

    - name: test if
      if: "contains(github.event.commits[0].message, '[e2e]')"
      run: |
        echo "contain [e2e]"