name: Build Template

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
      build-script:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      artifact-path:
        required: true
        type: string
      branch-name:
        required: true
        type: string

jobs:
  build-template:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-name }}
      - name: check branch
        run: |
          git branch
      - uses: ./.github/actions/common-steps

      - name: Build
        run: ${{ inputs.run }} ${{ inputs.build-script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
