name: Build Template

on:
  workflow_call:
    inputs:
      run:
        required: true
        type: string
      build-script:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      artifact-path:
        required: true
        type: string

jobs:
  build-template:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Display latest commit
        run: |
          git log
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: check branch
        run: |
          git log

      - uses: actions/cache@v4
        with:
          path: |
            node_modules/
            .pnpm-store
          key: ${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build
        run: ${{ inputs.run }} ${{ inputs.build-script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
