name: test

on:
  workflow_dispatch:

jobs:
  checkout-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: get_version
        env:
          current_version: "1.1.1"
        with:
          script: |
            const { current_version } = process.env

            console.log(`Hello ${current_version}`)
            const versionArr = current_version.split('.')
            versionArr[versionArr.length - 1] = 0
            const result = versionArr.join('.')
            return result
      - name: Get result
        run: echo "${{steps.get_version.outputs.result}}" 