name: test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.get_version.outputs.result }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v7
        id: get_version
        env:
          current_version: '1.1.1'
        with:
          script: |
            const { current_version } = process.env
            const versionArr = current_version.split('.')
            versionArr[versionArr.length - 1] = 0
            const result = versionArr.join('.')
            return result
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"