name: Create and Release Tag

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "GITHUB_REF=release/1.1.1" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: |
          echo $GITHUB_REF
          echo "${{ env.GITHUB_REF }}"
